#!/bin/bash

sudo apt install -y cmake gcc g++ automake autoconf libtool make build-essential wget libgtk-4-dev unzip wget
wget https://github.com/ZhuYanzhen1/EDA_Challenge/releases/download/gtest/gtest.zip
unzip gtest.zip && rm gtest.zip
