#!/bin/bash

sudo apt update && sudo apt -y upgrade
sudo apt install -y cmake gcc g++ automake autoconf libtool make build-essential wget libgtk-3-dev unzip wget
sudo apt install -y libxml2-utils libgtkmm-3.0-dev meson libplplot-dev plplot-driver-cairo valgrind
sudo snap install massif-visualizer --edge
wget https://github.com/ZhuYanzhen1/EDA_Challenge/releases/download/gtest/gtest.zip
rm -rf gtest && unzip gtest.zip && rm gtest.zip

# shellcheck disable=SC2164
mkdir testcase && cd testcase
wget https://github.com/ZhuYanzhen1/EDA_Challenge/releases/download/testcase/testcase_small.7z
7z x testcase_small.7z && rm testcase_small.7z && cd ..

wget https://github.com/tschoonj/gtkmm-plplot/releases/download/gtkmm-plplot-2.5/gtkmm-plplot-2.5.tar.gz
tar xfvz gtkmm-plplot-2.5.tar.gz && rm gtkmm-plplot-2.5.tar.gz
# shellcheck disable=SC2164
cd gtkmm-plplot-2.5 && mkdir -p build && cd build && meson ..
ninja && sudo ninja install && cd ../.. && rm -rf gtkmm-plplot-2.5

# shellcheck disable=SC2164
rm -rf build && mkdir -p build && cd build
cmake .. && cmake --build . --target version_h
cmake ..
