#!/bin/sh
for user in /home/*
do
    cp /usr/share/applications/Template.desktop ${user}/Desktop/
    chmod 755 ${user}/Desktop/Template.desktop
    chown ${user#/home/} ${user}/Desktop/Template.desktop
done

