EDA_Challenge: MiscFeat Class Reference
MiscFeat Class Reference
Miscellaneous functional class.
#include <misc_feat.h>
Static Public Member Functions
static void display_software_info (const std::string &version)
Show software system compilation time and version.
static bool file_exists (const std::string &filename)
Determine whether a file exists.
static void set_priority_to_max () noexcept
Set the priority of the process to the highest.
static void check_time_range_exists (CLIParser *cli_parser, VCDParser *vcd_parser, uint64_t *begin, uint64_t *end)
Check if the time units are equal and calculate the corresponding timestamp range.
Static Private Member Functions
static bool write_all_bytes_ (const char *path, const void *data) noexcept
Append information to a file.
Detailed Description
Miscellaneous functional class.
Definition at line 17 of file misc_feat.h.
Member Function Documentation
check_time_range_exists()
void MiscFeat::check_time_range_exists (CLIParser * cli_parser, VCDParser * vcd_parser, uint64_t * begin, uint64_t * end) static
Check if the time units are equal and calculate the corresponding timestamp range.
Parameters
[in] cli_parser Command line parser structure pointer
[in] vcd_parser VCD parser structure pointer
[out] begin Converted starting timestamp
[out] end Converted ending timestamp
Definition at line 79 of file misc_feat.cc.
References CLITimeStruct::begin_time, CLITimeStruct::begin_time_unit, CLITimeStruct::end_time, CLITimeStruct::end_time_unit, CLIParser::get_time_range(), VCDParser::get_vcd_header(), VCDHeaderStruct::vcd_time_scale, and VCDHeaderStruct::vcd_time_unit.
display_software_info()
void MiscFeat::display_software_info (const std::string & version) static
Show software system compilation time and version.
Definition at line 23 of file misc_feat.cc.
file_exists()
bool MiscFeat::file_exists (const std::string & filename) static
Determine whether a file exists.
Returns
Whether a file exists
Definition at line 36 of file misc_feat.cc.
Referenced by CLIParser::CLIParser().
set_priority_to_max()
void MiscFeat::set_priority_to_max () static noexcept
Set the priority of the process to the highest.
Definition at line 58 of file misc_feat.cc.
References write_all_bytes_().
Referenced by main().
write_all_bytes_()
bool MiscFeat::write_all_bytes_ (const char * path, const void * data) static private noexcept
Append information to a file.
Returns
Is the write file successful
Definition at line 45 of file misc_feat.cc.
Referenced by set_priority_to_max().
The documentation for this class was generated from the following files:
system/misc_feat.h
system/misc_feat.cc