EDA_Challenge: VCDParser Class Reference
VCDParser Class Reference
VCD parser class, which contains all the VCD file parsing functions.
#include <vcd_parser.h>
Classes
struct vcd_header_struct_
File header information for VCD files.
Public Member Functions
VCDParser (const std::string &filename)
Constructor for the VCD parser class, which opens the VCD file and parses the VCD header.
~VCDParser ()
The destructor function of the VCD parser class, which clears all the hash tables to free memory.
struct VCDHeaderStruct * get_vcd_header ()
Returns the information in the VCD file header.
tsl::hopscotch_map< std::string, struct VCDSignalStatisticStruct > * get_signal_flip_table ()
Returns a statistical hash table of all signals, used only in regression tests.
void get_vcd_scope ()
Get all modules and information of signals and store them in a list.
void get_vcd_scope (bool enable_gitch)
Get all modules and information of signals and store them in a list.(with glitch)
void get_vcd_scope (const std::string &module_label)
Get specified scope contains information of signals and store them in a hash table.
void get_vcd_scope (const std::string &module_label, bool enable_gitch)
Get specified scope contains information of signals and store them in a hash table. (with glitch)
void get_vcd_signal_flip_info ()
Total Signal Parse Function.
void get_vcd_signal_flip_info (bool enable_gitch)
Total Signal Parse Function (with glitch)
void get_vcd_signal_flip_info (const std::string &module_label)
Parse Signal by Scope Function.
void get_vcd_signal_flip_info (const std::string &module_label, bool enable_gitch)
Parse Signal by Scope Function (with glitch)
void get_vcd_signal_flip_info (uint64_t begin_time, uint64_t end_time)
Parse Signal by Time Range Function.
void get_vcd_signal_flip_info (uint64_t begin_time, uint64_t end_time, bool enable_gitch)
Parse Signal by Time Range Function (with glitch)
void get_vcd_signal_flip_info (const std::string &module_label, uint64_t begin_time, uint64_t end_time)
Parse Signal by Time Range and Scope Function.
void get_vcd_signal_flip_info (const std::string &module_label, uint64_t begin_time, uint64_t end_time, bool enable_gitch)
Parse Signal by Time Range and Scope Function (with glitch)
void printf_source_csv (const std::string &filepath)
Output the stored and counted results to file.
void printf_glitch_csv (const std::string &filepath)
Output glitch.csv file.
VCDSignalStatisticStruct * get_signal_flip_info (const std::string &signal_alias)
Returns the signal statistics for the specified alias, used only in unit tests.
void get_total_flips_in_time_range (uint64_t begin_time, uint64_t end_time, std::vector< double > *x_value, std::vector< double > *y_value)
Returns a vector of the number of signal reversals over a period of time.
Private Member Functions
void parse_vcd_header_ ()
Parse VCD file headers to obtain information such as time scaling factors.
void initialize_vcd_signal_flip_table_ ()
Get the signal initialization information and store it in the hash table, and execute it at zero time.
void initialize_vcd_signal_flip_table_ (bool enable_gitch)
Get the signal initialization information and store it in the hash table, and execute it at zero time (with glitch)
void initialize_vcd_signal_flip_table_ (const std::string &module_label)
Get the signal initialization information and store it in the hash table, and execute it at zero time.
void initialize_vcd_signal_flip_table_ (const std::string &module_label, bool enable_gitch)
Get the signal initialization information and store it in the hash table, and execute it at zero time (with glitch)
void vcd_signal_flip_post_processing_ (uint64_t timestamp)
Count signal flip by post processing pattern.
void vcd_signal_flip_post_processing_ (uint64_t timestamp, tsl::hopscotch_map< std::string, int8_t > *burr_hash_table)
Count signal flip by post processing pattern.
void vcd_statistic_glitch_ (tsl::hopscotch_map< std::string, int8_t > *burr_hash_table, uint64_t current_timestamp)
Count the signals and timestamps in the temporary glitch list into the global glitch hash table.
Static Private Member Functions
static void vcd_statistic_signal_ (uint64_t current_timestamp, struct VCDSignalStatisticStruct *signal, char current_level_status, const std::string &signal_alias)
Statistic vcd signals.
static void vcd_statistic_signal_ (uint64_t current_timestamp, struct VCDSignalStatisticStruct *signal, tsl::hopscotch_map< std::string, int8_t > *burr_hash_table, char current_level_status, const std::string &signal_alias)
Statistic vcd signals (with glitch)
Private Attributes
FILE * fp_
File stream structure for VCD files.
std::list< std::pair< std::string, tsl::hopscotch_map< std::string, struct VCDSignalStruct > > > vcd_signal_list_
Module hierarchy list for VCD signals.
tsl::hopscotch_map< std::string, struct VCDSignalStatisticStruct > vcd_signal_flip_table_
Hash table for VCD signal statistics.
tsl::hopscotch_map< std::string, int8_t > vcd_signal_alias_table_
Hash table of signals to be counted when counting by module.
tsl::hopscotch_map< std::string, std::list< uint64_t > > signal_glitch_position_
Hash table for storing the moment of glitch of the signal.
tsl::hopscotch_map< std::string, struct VCDGlitchStruct > signal_glitch_table_
Signal name hierarchy information for signals glitch.
uint64_t total_time_ {}
Total duration of the VCD file.
long second_position_ {}
Location of the second timestamp in the file.
Detailed Description
VCD parser class, which contains all the VCD file parsing functions.
Definition at line 66 of file vcd_parser.h.
Constructor & Destructor Documentation
VCDParser()
VCDParser::VCDParser (const std::string & filename) inline explicit
Constructor for the VCD parser class, which opens the VCD file and parses the VCD header.
Definition at line 70 of file vcd_parser.h.
References fp_, and parse_vcd_header_().
~VCDParser()
VCDParser::~VCDParser () inline
The destructor function of the VCD parser class, which clears all the hash tables to free memory.
Definition at line 79 of file vcd_parser.h.
References fp_, signal_glitch_position_, vcd_signal_alias_table_, vcd_signal_flip_table_, and vcd_signal_list_.
Member Function Documentation
get_signal_flip_info()
VCDSignalStatisticStruct * VCDParser::get_signal_flip_info (const std::string & signal_alias)
Returns the signal statistics for the specified alias, used only in unit tests.
Parameters
[in] signal_alias Start time of time range.
Returns
Signal statistics of this alias.
Definition at line 976 of file vcd_parser.cc.
References vcd_signal_flip_table_.
get_signal_flip_table()
tsl::hopscotch_map< std::string, struct VCDSignalStatisticStruct > * VCDParser::get_signal_flip_table () inline
Returns a statistical hash table of all signals, used only in regression tests.
Returns
Hash table of all signals.
Definition at line 99 of file vcd_parser.h.
References vcd_signal_flip_table_.
get_total_flips_in_time_range()
void VCDParser::get_total_flips_in_time_range (uint64_t begin_time, uint64_t end_time, std::vector< double > * x_value, std::vector< double > * y_value)
Returns a vector of the number of signal reversals over a period of time.
Parameters
[in] begin_time Start time of time range.
[in] end_time End time of time range.
[in,out] x_value The returned x-axis vector.
[in,out] y_value The returned y-axis vector.
Definition at line 988 of file vcd_parser.cc.
References fp_, and reading_buffer.
get_vcd_header()
struct VCDHeaderStruct * VCDParser::get_vcd_header () inline
Returns the information in the VCD file header.
Returns
VCD file header information.
Definition at line 91 of file vcd_parser.h.
Referenced by MiscFeat::check_time_range_exists().
get_vcd_scope() [1/4]
void VCDParser::get_vcd_scope ()
Get all modules and information of signals and store them in a list.
Definition at line 297 of file vcd_parser.cc.
References fp_, VCDSignalStruct::next_signal, reading_buffer, vcd_signal_list_, and VCDSignalStruct::vcd_signal_title.
get_vcd_scope() [2/4]
void VCDParser::get_vcd_scope (bool enable_gitch)
Get all modules and information of signals and store them in a list.(with glitch)
Parameters
[in] enable_gitch A bool value that determine whether to output a glitch
Definition at line 298 of file vcd_parser_glitch.cc.
References VCDGlitchStruct::all_module_signal, VCDGlitchStruct::declare_width_start, fp_, VCDSignalStruct::next_signal, reading_buffer, signal_glitch_table_, vcd_signal_list_, and VCDSignalStruct::vcd_signal_title.
get_vcd_scope() [3/4]
void VCDParser::get_vcd_scope (const std::string & module_label)
Get specified scope contains information of signals and store them in a hash table.
Parameters
[in] module_label Input scope name
Definition at line 417 of file vcd_parser.cc.
References VCDGlitchStruct::all_module_signal, VCDGlitchStruct::declare_width_start, fp_, VCDSignalStruct::next_signal, reading_buffer, signal_glitch_table_, vcd_signal_alias_table_, vcd_signal_list_, and VCDSignalStruct::vcd_signal_title.
get_vcd_scope() [4/4]
void VCDParser::get_vcd_scope (const std::string & module_label, bool enable_gitch)
Get specified scope contains information of signals and store them in a hash table. (with glitch)
Parameters
[in] module_label The name of the specified scope
[in] enable_gitch A bool value that determine whether to output a glitch
Definition at line 443 of file vcd_parser_glitch.cc.
References fp_, VCDSignalStruct::next_signal, reading_buffer, vcd_signal_alias_table_, vcd_signal_list_, and VCDSignalStruct::vcd_signal_title.
get_vcd_signal_flip_info() [1/8]
void VCDParser::get_vcd_signal_flip_info ()
Total Signal Parse Function.
Definition at line 592 of file vcd_parser.cc.
References fp_, initialize_vcd_signal_flip_table_(), reading_buffer, second_position_, vcd_signal_flip_post_processing_(), vcd_signal_flip_table_, and vcd_statistic_signal_().
get_vcd_signal_flip_info() [2/8]
void VCDParser::get_vcd_signal_flip_info (bool enable_gitch)
Total Signal Parse Function (with glitch)
Parameters
[in] enable_gitch A bool value that determine whether to output a glitch
Definition at line 607 of file vcd_parser_glitch.cc.
References fp_, initialize_vcd_signal_flip_table_(), reading_buffer, second_position_, signal_glitch_position_, vcd_signal_flip_post_processing_(), vcd_signal_flip_table_, vcd_statistic_glitch_(), and vcd_statistic_signal_().
get_vcd_signal_flip_info() [3/8]
void VCDParser::get_vcd_signal_flip_info (const std::string & module_label)
Parse Signal by Scope Function.
Parameters
[in] module_label Input module name
Definition at line 641 of file vcd_parser.cc.
References fp_, initialize_vcd_signal_flip_table_(), reading_buffer, second_position_, vcd_signal_alias_table_, vcd_signal_flip_post_processing_(), vcd_signal_flip_table_, and vcd_statistic_signal_().
get_vcd_signal_flip_info() [4/8]
void VCDParser::get_vcd_signal_flip_info (const std::string & module_label, bool enable_gitch)
Parse Signal by Scope Function (with glitch)
Parameters
[in] module_label Input module name
[in] enable_gitch A bool value that determine whether to output a glitch
Definition at line 663 of file vcd_parser_glitch.cc.
References fp_, initialize_vcd_signal_flip_table_(), reading_buffer, second_position_, signal_glitch_position_, vcd_signal_alias_table_, vcd_signal_flip_post_processing_(), vcd_signal_flip_table_, vcd_statistic_glitch_(), and vcd_statistic_signal_().
get_vcd_signal_flip_info() [5/8]
void VCDParser::get_vcd_signal_flip_info (const std::string & module_label, uint64_t begin_time, uint64_t end_time)
Parse Signal by Time Range and Scope Function.
Parameters
[in] module_label Input module name
[in] begin_time Begin time of the parsing process
[in] end_time End time of the parsing process
Definition at line 780 of file vcd_parser.cc.
References fp_, initialize_vcd_signal_flip_table_(), reading_buffer, total_time_, vcd_signal_alias_table_, vcd_signal_flip_post_processing_(), vcd_signal_flip_table_, and vcd_statistic_signal_().
get_vcd_signal_flip_info() [6/8]
void VCDParser::get_vcd_signal_flip_info (const std::string & module_label, uint64_t begin_time, uint64_t end_time, bool enable_gitch)
Parse Signal by Time Range and Scope Function (with glitch)
Parameters
[in] module_label Input scope name
[in] begin_time Begin time of the parsing process
[in] end_time End time of the parsing process
[in] enable_gitch A bool value that determine whether to output a glitch
Definition at line 818 of file vcd_parser_glitch.cc.
References fp_, initialize_vcd_signal_flip_table_(), reading_buffer, second_position_, signal_glitch_position_, total_time_, vcd_signal_alias_table_, vcd_signal_flip_post_processing_(), vcd_signal_flip_table_, vcd_statistic_glitch_(), and vcd_statistic_signal_().
get_vcd_signal_flip_info() [7/8]
void VCDParser::get_vcd_signal_flip_info (uint64_t begin_time, uint64_t end_time)
Parse Signal by Time Range Function.
Parameters
[in] begin_time Begin time of the parsing process
[in] end_time End time of the parsing process
Definition at line 691 of file vcd_parser.cc.
References fp_, initialize_vcd_signal_flip_table_(), reading_buffer, second_position_, total_time_, vcd_signal_flip_post_processing_(), vcd_signal_flip_table_, and vcd_statistic_signal_().
get_vcd_signal_flip_info() [8/8]
void VCDParser::get_vcd_signal_flip_info (uint64_t begin_time, uint64_t end_time, bool enable_gitch)
Parse Signal by Time Range Function (with glitch)
Parameters
[in] begin_time Begin time of the parsing process
[in] end_time End time of the parsing process
[in] enable_gitch A bool value that determine whether to output a glitch
Definition at line 719 of file vcd_parser_glitch.cc.
References fp_, initialize_vcd_signal_flip_table_(), reading_buffer, second_position_, signal_glitch_position_, total_time_, vcd_signal_flip_post_processing_(), vcd_signal_flip_table_, vcd_statistic_glitch_(), and vcd_statistic_signal_().
initialize_vcd_signal_flip_table_() [1/4]
void VCDParser::initialize_vcd_signal_flip_table_ () private
Get the signal initialization information and store it in the hash table, and execute it at zero time.
Definition at line 117 of file vcd_parser.cc.
References fp_, reading_buffer, second_position_, and vcd_signal_flip_table_.
Referenced by get_vcd_signal_flip_info().
initialize_vcd_signal_flip_table_() [2/4]
void VCDParser::initialize_vcd_signal_flip_table_ (bool enable_gitch) private
Get the signal initialization information and store it in the hash table, and execute it at zero time (with glitch)
Parameters
[in] enable_gitch A bool value that determine whether to output a glitch
Definition at line 63 of file vcd_parser_glitch.cc.
References fp_, reading_buffer, second_position_, vcd_signal_flip_table_, and vcd_statistic_glitch_().
initialize_vcd_signal_flip_table_() [3/4]
void VCDParser::initialize_vcd_signal_flip_table_ (const std::string & module_label) private
Get the signal initialization information and store it in the hash table, and execute it at zero time.
Parameters
[in] module_label Input module name
Definition at line 190 of file vcd_parser.cc.
References fp_, reading_buffer, second_position_, vcd_signal_alias_table_, and vcd_signal_flip_table_.
initialize_vcd_signal_flip_table_() [4/4]
void VCDParser::initialize_vcd_signal_flip_table_ (const std::string & module_label, bool enable_gitch) private
Get the signal initialization information and store it in the hash table, and execute it at zero time (with glitch)
Parameters
[in] module_label Input scope name
[in] enable_gitch A bool value that determine whether to output a glitch
Definition at line 152 of file vcd_parser_glitch.cc.
References fp_, reading_buffer, second_position_, vcd_signal_alias_table_, vcd_signal_flip_table_, and vcd_statistic_glitch_().
parse_vcd_header_()
void VCDParser::parse_vcd_header_ () private
Parse VCD file headers to obtain information such as time scaling factors.
Definition at line 23 of file vcd_parser.cc.
References fp_, and reading_buffer.
Referenced by VCDParser().
printf_glitch_csv()
void VCDParser::printf_glitch_csv (const std::string & filepath)
Output glitch.csv file.
Definition at line 920 of file vcd_parser_glitch.cc.
References signal_glitch_position_, and signal_glitch_table_.
printf_source_csv()
void VCDParser::printf_source_csv (const std::string & filepath)
Output the stored and counted results to file.
Parameters
[in] filepath The position to output source.csv file.
Definition at line 876 of file vcd_parser.cc.
References VCDSignalStatisticStruct::signal0_time, VCDSignalStatisticStruct::signal1_time, VCDSignalStatisticStruct::signalx_time, VCDSignalStatisticStruct::total_glitch_counter, VCDSignalStatisticStruct::total_invert_counter, total_time_, vcd_signal_flip_table_, and vcd_signal_list_.
vcd_signal_flip_post_processing_() [1/2]
void VCDParser::vcd_signal_flip_post_processing_ (uint64_t current_timestamp) private
Count signal flip by post processing pattern.
Parameters
[in] current_timestamp The current timestamp at which the signal was processed
Definition at line 267 of file vcd_parser.cc.
References total_time_, and vcd_signal_flip_table_.
Referenced by get_vcd_signal_flip_info().
vcd_signal_flip_post_processing_() [2/2]
void VCDParser::vcd_signal_flip_post_processing_ (uint64_t current_timestamp, tsl::hopscotch_map< std::string, int8_t > * burr_hash_table) private
Count signal flip by post processing pattern.
Parameters
[in] current_timestamp time in current parsing section.
[in] burr_hash_table a hash table to store glitches' information.
Definition at line 263 of file vcd_parser_glitch.cc.
References total_time_, vcd_signal_flip_table_, and vcd_statistic_glitch_().
vcd_statistic_glitch_()
void VCDParser::vcd_statistic_glitch_ (tsl::hopscotch_map< std::string, int8_t > * burr_hash_table, uint64_t current_timestamp) private
Count the signals and timestamps in the temporary glitch list into the global glitch hash table.
Parameters
[in] burr_hash_table a hash table to store glitches' information.
[in] current_timestamp time in current parsing section.
Definition at line 244 of file vcd_parser_glitch.cc.
References signal_glitch_position_.
Referenced by get_vcd_signal_flip_info(), initialize_vcd_signal_flip_table_(), and vcd_signal_flip_post_processing_().
vcd_statistic_signal_() [1/2]
void VCDParser::vcd_statistic_signal_ (uint64_t current_timestamp, struct VCDSignalStatisticStruct * signal, char current_level_status, const std::string & signal_alias) static private
Statistic vcd signals.
Parameters
[in] current_timestamp The current timestamp at which the signal was processed
[in] signal A struct to store signals' flip information
[in] current_level_status The current status of the input signal
[in] signal_alias Input signal's identifier
Definition at line 85 of file vcd_parser.cc.
References VCDSignalStatisticStruct::final_level_status, VCDSignalStatisticStruct::last_level_status, VCDSignalStatisticStruct::last_timestamp, VCDSignalStatisticStruct::signal0_time, VCDSignalStatisticStruct::signal1_time, VCDSignalStatisticStruct::signalx_time, and VCDSignalStatisticStruct::total_invert_counter.
Referenced by get_vcd_signal_flip_info().
vcd_statistic_signal_() [2/2]
void VCDParser::vcd_statistic_signal_ (uint64_t current_timestamp, struct VCDSignalStatisticStruct * signal, tsl::hopscotch_map< std::string, int8_t > * burr_hash_table, char current_level_status, const std::string & signal_alias) static private
Statistic vcd signals (with glitch)
Parameters
[in] current_timestamp The current timestamp at which the signal was processed
[in] signal A struct to store signals' flip information
[in] burr_hash_table Temporary hash table for glitch statistics
[in] current_level_status The current status of the input signal
[in] signal_alias Input signal's identifier
Definition at line 28 of file vcd_parser_glitch.cc.
References VCDSignalStatisticStruct::final_level_status, VCDSignalStatisticStruct::last_level_status, VCDSignalStatisticStruct::last_timestamp, VCDSignalStatisticStruct::signal0_time, VCDSignalStatisticStruct::signal1_time, VCDSignalStatisticStruct::signalx_time, VCDSignalStatisticStruct::total_glitch_counter, and VCDSignalStatisticStruct::total_invert_counter.
Member Data Documentation
fp_
FILE* VCDParser::fp_ private
File stream structure for VCD files.
Definition at line 126 of file vcd_parser.h.
Referenced by get_total_flips_in_time_range(), get_vcd_scope(), get_vcd_signal_flip_info(), initialize_vcd_signal_flip_table_(), parse_vcd_header_(), VCDParser(), and ~VCDParser().
second_position_
long VCDParser::second_position_ {} private
Location of the second timestamp in the file.
Definition at line 150 of file vcd_parser.h.
Referenced by get_vcd_signal_flip_info(), and initialize_vcd_signal_flip_table_().
signal_glitch_position_
tsl::hopscotch_map<std::string, std::list<uint64_t> > VCDParser::signal_glitch_position_ private
Hash table for storing the moment of glitch of the signal.
Definition at line 141 of file vcd_parser.h.
Referenced by get_vcd_signal_flip_info(), printf_glitch_csv(), vcd_statistic_glitch_(), and ~VCDParser().
signal_glitch_table_
tsl::hopscotch_map<std::string, struct VCDGlitchStruct> VCDParser::signal_glitch_table_ private
Signal name hierarchy information for signals glitch.
Definition at line 144 of file vcd_parser.h.
Referenced by get_vcd_scope(), and printf_glitch_csv().
total_time_
uint64_t VCDParser::total_time_ {} private
Total duration of the VCD file.
Definition at line 147 of file vcd_parser.h.
Referenced by get_vcd_signal_flip_info(), printf_source_csv(), and vcd_signal_flip_post_processing_().
vcd_signal_alias_table_
tsl::hopscotch_map<std::string, int8_t> VCDParser::vcd_signal_alias_table_ private
Hash table of signals to be counted when counting by module.
Definition at line 138 of file vcd_parser.h.
Referenced by get_vcd_scope(), get_vcd_signal_flip_info(), initialize_vcd_signal_flip_table_(), and ~VCDParser().
vcd_signal_flip_table_
tsl::hopscotch_map<std::string, struct VCDSignalStatisticStruct> VCDParser::vcd_signal_flip_table_ private
Hash table for VCD signal statistics.
Definition at line 135 of file vcd_parser.h.
Referenced by get_signal_flip_info(), get_signal_flip_table(), get_vcd_signal_flip_info(), initialize_vcd_signal_flip_table_(), printf_source_csv(), vcd_signal_flip_post_processing_(), and ~VCDParser().
vcd_signal_list_
std::list<std::pair<std::string, tsl::hopscotch_map<std::string, struct VCDSignalStruct> > > VCDParser::vcd_signal_list_ private
Module hierarchy list for VCD signals.
Definition at line 132 of file vcd_parser.h.
Referenced by get_vcd_scope(), printf_source_csv(), and ~VCDParser().
The documentation for this class was generated from the following files:
parser/vcd_parser.h
parser/vcd_parser.cc
parser/vcd_parser_glitch.cc