EDA_Challenge: main.cc File Reference
main.cc File Reference
This source file is the program entry file.
#include "gtest/gtest.h"
Functions
int main (int argc, char **argv)
Program entry.
Detailed Description
This source file is the program entry file.
Author
Yanzhen Zhu
Version
V1.0.1
Date
21. November 2022
Definition in file main.cc.
Function Documentation
main()
int main (int argc, char ** argv)
Program entry.
Parameters
[in] argc Number of command-line arguments sent to the main function at program runtime
[in] argv Store an array of pointers to string parameters
Returns
Program execution results
Definition at line 116 of file main.cc.
References MiscFeat::set_priority_to_max(), CLIParser::using_gui(), and CLIParser::using_multithread().