name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - uses: actions/checkout@v3
      - name: Display Files
        run: |
          ls
          cd /home/public && du -h --max-depth=1
