name: Compile

on:
  push:
    branches:
      - main
  schedule:
    - cron: '40 15 * * *'      # compile at 23:50 each day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure Software
        run: |
          sudo apt-get update && sudo apt-get -y upgrade
          sudo apt-get install -y cmake gcc g++ automake autoconf libtool make build-essential wget libgtk-3-dev
          sudo apt install unzip wget libxml2-utils libgtkmm-3.0-dev meson plplot-driver-cairo libplplot-dev -y
          wget https://github.com/ZhuYanzhen1/EDA_Challenge/releases/download/gtest/gtest.zip
          unzip gtest.zip && rm gtest.zip
          wget https://github.com/tschoonj/gtkmm-plplot/releases/download/gtkmm-plplot-2.5/gtkmm-plplot-2.5.tar.gz
          tar xfvz gtkmm-plplot-2.5.tar.gz && rm gtkmm-plplot-2.5.tar.gz
          cd gtkmm-plplot-2.5 && mkdir build && cd build && meson ..
          ninja && sudo ninja install && cd ../.. && rm -rf gtkmm-plplot-2.5
          mkdir build && cd build && cmake ..
      - name: Build Software
        run: |
          cd build && cmake --build . --target version_h && cmake .. && cmake --build . --target EDA_Challenge -j$(nproc)
          cmake --build . --target Google_Test -j$(nproc)
      - name: Run Software
        run: |
          ls && cd build && ls && ./EDA_Challenge -v && ./EDA_Challenge -h
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: EDA_Challenge-bin
          path: build/Google_Test
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/download-artifact@v2
        with:
          name: EDA_Challenge-bin
          path: ./
      - name: Install gtest
        run: |
          ls && sudo apt install p7zip-full -y && mkdir testcase && cd testcase
          wget https://github.com/ZhuYanzhen1/EDA_Challenge/releases/download/testcase/testcase_small.7z
          7z x testcase_small.7z && rm testcase_small.7z && cd ..
      - name: Running gtest
        run: |
          ls && ./Google_Test
