name: Compile

on:
  push:
    branches:
      - main
  schedule:
    - cron: '40 15 * * *'      # compile at 23:50 each day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure Software
        run: |
          sudo apt-get update && sudo apt-get -y upgrade
          sudo apt-get install -y cmake gcc g++ automake autoconf libtool make build-essential wget libgtk-3-dev
          sudo apt install unzip wget libxml2-utils libgtkmm-3.0-dev -y
          wget https://github.com/ZhuYanzhen1/EDA_Challenge/releases/download/gtest/gtest.zip
          unzip gtest.zip && rm gtest.zip
          mkdir build && cd build && cmake ..
      - name: Build Software
        run: |
          cd build && cmake --build . --target version_h && cmake .. && cmake --build . --target EDA_Challenge -j$(nproc)
      - name: Run Software
        run: |
          ls && cd build && ls && ./EDA_Challenge -v && ./EDA_Challenge -h && ./EDA_Challenge -f ../testcase/case0/test.vcd
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install gtest
        run: |
          ls
